//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	public class AnimatorConstants
	{

		public static int DAMAGED = Animator.StringToHash("Damage");
		public static int GET_GROUNDED = Animator.StringToHash("getGrounded");
		public static int GROUNDED = Animator.StringToHash("Grounded");
		public static int VELOCITY_Y = Animator.StringToHash("VelocityY");
		public static int DOUBLE_JUMPED = Animator.StringToHash("DoubleJump");
		public static int JUMPED = Animator.StringToHash("Jump");
		public static int BLOCKED = Animator.StringToHash("Block");
		public static int FATIGUE = Animator.StringToHash("TriggerFatiegue");
		public static int SLASH = Animator.StringToHash("TriggerSlash");
		public static int SLASH_TYPE = Animator.StringToHash("SlashType");
		public static int THROW = Animator.StringToHash("TriggerThrow");
		public static int CLASH = Animator.StringToHash("TriggerClash");
		public static int THROW_UP = Animator.StringToHash("TriggerThrowUp");
		public static int DAMAGE_SLASH = Animator.StringToHash("TriggerDamageSlash");
		public static int DAMAGE_THROW = Animator.StringToHash("TriggerDamageThrow");
		public static int WIN = Animator.StringToHash("TriggerWin");
		public static int DIE = Animator.StringToHash("TriggerDead");
		public static int SUPERMOVE_START = Animator.StringToHash("SuperMoveStart");
		public static int SUPERMOVE_FLY = Animator.StringToHash("SuperMoveFly");
		public static int SUPERMOVE_ATTACK = Animator.StringToHash("SuperMoveAttack");
		public static int WALL_HUGGGING = Animator.StringToHash("WallHugging");
		public static int DEAD = Animator.StringToHash("Dead");
		public static int CORPSE_WATER = Animator.StringToHash("CorpseWater");
		public static int CORPSE_OTHER = Animator.StringToHash("CorpseOther");
		public static int DASH = Animator.StringToHash("DashTrigger");
		public static int L_XAXIS = Animator.StringToHash("L_XAXIS");
		public static int L_YAXIS = Animator.StringToHash("L_YAXIS");
		public static int X_INPUT = Animator.StringToHash("X_INPUT");
		public static int Y_INPUT = Animator.StringToHash("Y_INPUT");
		public static int SLASHCHARGESTART = Animator.StringToHash("SlashStartCharge");	
		public static int CHARGED_COMPLETELY = Animator.StringToHash("CHARGED_COMPLETELY");	
		public static int GOT_PARIED = Animator.StringToHash("GOT_PARIED");	
		public static int PARIED_COMPLETE = Animator.StringToHash("PARRIED_COMPLETE");
		public static int TRANSFORM = Animator.StringToHash("TriggerTransform");
		
		public static int ICE_1 = Animator.StringToHash("ICE_1");
		public static int ICE_2 = Animator.StringToHash("ICE_2");
		public static int ICE_3 = Animator.StringToHash("ICE_3");
		/*public static int L_MAGNITUDE = Animator.StringToHash("L_MAGNITUDE");			
		public static int L_ANGLE = Animator.StringToHash("L_ANGLE");*/
	}
}

