//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


namespace AssemblyCSharp
{
	public class GameData
	{
		public static int currentLevel = 4;
		public static int lakeState = 0;
		public static bool bridgeBroken = false;
		public static bool dialoguePlayed = false;

		public static Dictionary<string, List<string> >  ghosts = new Dictionary<string, List<string> >
		{
			{ "lava", new List<string>() },
			{ "level3", new List<string>() },
			{ "level2", new List<string>() },
			{"demo", new List<string>() },
			{ "score", new List<string>() },
			{ "left", new List<string>() },
			{ "right", new List<string>() },
			{ "level4", new List<string>() },
			{ "summit", new List<string>()}, 
			{ "bamboo", new List<string>() },
			{ "beach", new List<string>() }
		};

		public static Dictionary<string, List<Corpse> >  corpses = new Dictionary<string, List<Corpse> >
		{
			{ "lava", new List<Corpse>() },
			{ "level3", new List<Corpse>() },
			{ "level2", new List<Corpse>() },
			{"demo", new List<Corpse>() },
			{ "score", new List<Corpse>() },
			{ "left", new List<Corpse>() },
			{ "right", new List<Corpse>() },
			{ "level4", new List<Corpse>() },
			{ "summit", new List<Corpse>()}, 
			{ "bamboo", new List<Corpse>() },
			{ "beach", new List<Corpse>() }
		};

		
		public static Dictionary<string, List<string> >  ices = new Dictionary<string, List<string> >
		{
			{ "level4", new List<string>() }
		};

		public static string[] levelData = new string[]
		{
			"score",
			"beach",
			"bamboo",
			"level2",
			"demo",
			"lava",
			"level4",
			"summit",
			"score"
		};
		
		public static void reset()
		{
			ghosts = new Dictionary<string, List<string>>();
			corpses = new Dictionary<string, List<Corpse>>();
			ices = new Dictionary<string, List<string>>();
		}
		
		public static void addGhost( string ghost )
		{
			ghosts[ levelData[currentLevel] ].Add( ghost );
		}
		
		public static List<string> getGhostsForCurrentLevel()
		{
			return ghosts[ levelData[currentLevel] ];
		}

		public static void addCorpse(Corpse newCorpse )
		{
			corpses[ levelData[currentLevel] ].Add(newCorpse );
		}
		
		public static List<Corpse> getCorpsesForCurrentLevel()
		{
			return corpses[ levelData[currentLevel] ];
		}

		public static void addIceCorpse(string newName)
		{
			ices["level4"].Add(newName);
		}

		public static List<string> getIceCorpses()
		{
			return ices["level4"];
		}

		public static void DestroyIce (int index)
		{
			ices["level4"].Remove(ices["level4"][index]);
		}

		                      
	}
}

