//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	public class GeekGUI
	{
		/// <summary>
		/// Shows a timed window (seconds)
		/// </summary>
		/// <returns>The window.</returns>
		/// <param name="title">Title.</param>
		/// <param name="time">Time.</param>
		public static GameObject timedWindow( string title, int time)
		{
			GameObject obj = new GameObject();
			TimedWindow window = obj.AddComponent<TimedWindow> ();
			
			window.duration = time;
			window.title = title;
			
			return obj;
		}
	}
}

