//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class ResourceConstants
	{
		public static string VILLAIN = "Villain";
		public static string HERO = "Hero";
		public static string HEROINE = "Heroine";
		public static string HENCHMAN = "HenchMan";
		public static string BANNER_HERO = "Samudai_Banner_Hero";
	}
}

