//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;


namespace AssemblyCSharp
{
	public class WaterfallSuddenDeath : SuddenDeath
	{
		public GameObject[] rocks;
		bool sinking = false;
		
		override public void Activate()
		{
			print ("activating suddenDeath");
			foreach( GameObject rock in rocks )
			{
				iTween.MoveTo( rock, iTween.Hash(
				"position", rock.transform.position - new Vector3(0, 7f ),
				"time", 7f,
				"easetype", iTween.EaseType.linear
				) );
			}
			
			sinking = true;
			
			
			iTween.ShakePosition (Camera.main.gameObject, new Hashtable{
				{ "time", 7 },
				{"amount", new Vector3( 0.3f, 0.3f ) }
			});
		}
		
		override protected void Update()
		{
			
		}
		
		void sinkRockComplete()
		{
			sinking = false;
			print ("sinkRockCompletE");
		}
	}
}

