//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class DeadStatusEffect : StatusEffect3
	{
		override protected void Start()
		{
			base.Start();
			GetComponent<GeekBehaviour>().dispatchMessage( PlayerC.M_INPUT_DISABLE);
			//dissable everything for when you're dead
		}
		
		override protected void Update()
		{
			base.Update();
		}
		
		override public void reset()
		{
			base.reset();
			GetComponent<GeekBehaviour>().dispatchMessage( PlayerC.M_INPUT_ENABLE);
			//re-enable everything when you come alive
		}
	}
}

