//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;


namespace AssemblyCSharp
{
	[RequireComponent (typeof (StatusEffectManager2))]
	public class StatusEffect2 : TimedScript
	{
		public Dictionary<int, dynamic> propertyValues;
		
		public static string M_STATUS_END = "M_STATUS_END";
		public static string M_STATUS_ENDED = "M_STATUS_ENDED";
		
		protected StatusEffectManager2 manager;
		public bool extendWhenStack = false;
		
		
		override protected void Start()
		{
			base.Start();
			
			propertyValues = new Dictionary<int, dynamic>();
			
			manager = GetComponent<StatusEffectManager2>();
//			manager.Register( this );
		}
		
		public void extend( float time = 0 )
		{
			timer.duration += duration;
		}
		
		public virtual void reset()
		{
		//	manager.RemoveEffect( this );
			//if( manager.containsSameType( GetType() ) ) return;
		}
		
		override protected void HandleonElapsed( LiteTimer timer)
		{
			Destroy( this );
		}
		
		override protected void Update()
		{
			base.Update();
		}
		
		/*void OnDisable()
		{
			dispatchMessage(M_STATUS_ENDED, this );
			reset();
		} */
		
		
		void OnDestroy()
		{
			dispatchMessage(M_STATUS_ENDED, this );
			reset();
		}
		
	}
}

